Add random card draws, opponent glowing eyes and player health
A-NGJ/ShadowRealm pull request #13
Opened 2023-05-02 18:26 UTC by lamkwjonathan

2023-05-02 22:33 UTC, A-NGJ requested changes

2023-05-02 22:33 UTC, A-NGJ commented on Assets/Scripts/GameManager.cs
>          gameText = GameObject.Find("GameText").GetComponent<TextMeshProUGUI>();
Either remove this line or change it to `GameStateText` object that you created and remove reference in Unity inspector. Anyway, keep it consistent with `healthText`

2023-05-02 23:31 UTC, lamkwjonathan commented on Assets/Scripts/GameManager.cs
>          gameText = GameObject.Find("GameText").GetComponent<TextMeshProUGUI>();
Removed!

2023-05-03 07:15 UTC, A-NGJ approved these changes

2023-05-03 08:41 UTC, merged